/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlindsRouteImport } from './routes/blinds'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CurtainRepairsRouteImport } from './routes/curtain-repairs'
import { Route as CurtainsRouteImport } from './routes/curtains'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as MotorisedCurtainsRouteImport } from './routes/motorised-curtains'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiQuoteRouteImport } from './routes/api/quote'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ZhHansIndexRouteImport } from './routes/zh-hans.index'
import { Route as ZhHansAboutRouteImport } from './routes/zh-hans.about'
import { Route as ZhHansBlindsRouteImport } from './routes/zh-hans.blinds'
import { Route as ZhHansContactRouteImport } from './routes/zh-hans.contact'
import { Route as ZhHansCurtainRepairsRouteImport } from './routes/zh-hans.curtain-repairs'
import { Route as ZhHansCurtainsRouteImport } from './routes/zh-hans.curtains'
import { Route as ZhHansGalleryRouteImport } from './routes/zh-hans.gallery'
import { Route as ZhHansMotorisedCurtainsRouteImport } from './routes/zh-hans.motorised-curtains'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlindsRoute = BlindsRouteImport.update({
  id: '/blinds',
  path: '/blinds',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CurtainRepairsRoute = CurtainRepairsRouteImport.update({
  id: '/curtain-repairs',
  path: '/curtain-repairs',
  getParentRoute: () => rootRouteImport,
} as any)
const CurtainsRoute = CurtainsRouteImport.update({
  id: '/curtains',
  path: '/curtains',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const MotorisedCurtainsRoute = MotorisedCurtainsRouteImport.update({
  id: '/motorised-curtains',
  path: '/motorised-curtains',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuoteRoute = ApiQuoteRouteImport.update({
  id: '/api/quote',
  path: '/api/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhHansIndexRoute = ZhHansIndexRouteImport.update({
  id: '/zh-hans/',
  path: '/zh-hans/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhHansAboutRoute = ZhHansAboutRouteImport.update({
  id: '/zh-hans/about',
  path: '/zh-hans/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhHansBlindsRoute = ZhHansBlindsRouteImport.update({
  id: '/zh-hans/blinds',
  path: '/zh-hans/blinds',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhHansContactRoute = ZhHansContactRouteImport.update({
  id: '/zh-hans/contact',
  path: '/zh-hans/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhHansCurtainRepairsRoute = ZhHansCurtainRepairsRouteImport.update({
  id: '/zh-hans/curtain-repairs',
  path: '/zh-hans/curtain-repairs',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhHansCurtainsRoute = ZhHansCurtainsRouteImport.update({
  id: '/zh-hans/curtains',
  path: '/zh-hans/curtains',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhHansGalleryRoute = ZhHansGalleryRouteImport.update({
  id: '/zh-hans/gallery',
  path: '/zh-hans/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhHansMotorisedCurtainsRoute = ZhHansMotorisedCurtainsRouteImport.update({
  id: '/zh-hans/motorised-curtains',
  path: '/zh-hans/motorised-curtains',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blinds': typeof BlindsRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/curtain-repairs': typeof CurtainRepairsRoute
  '/curtains': typeof CurtainsRoute
  '/gallery': typeof GalleryRoute
  '/motorised-curtains': typeof MotorisedCurtainsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/quote': typeof ApiQuoteRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/zh-hans/about': typeof ZhHansAboutRoute
  '/zh-hans/blinds': typeof ZhHansBlindsRoute
  '/zh-hans/contact': typeof ZhHansContactRoute
  '/zh-hans/curtain-repairs': typeof ZhHansCurtainRepairsRoute
  '/zh-hans/curtains': typeof ZhHansCurtainsRoute
  '/zh-hans/gallery': typeof ZhHansGalleryRoute
  '/zh-hans/motorised-curtains': typeof ZhHansMotorisedCurtainsRoute
  '/zh-hans/': typeof ZhHansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blinds': typeof BlindsRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/curtain-repairs': typeof CurtainRepairsRoute
  '/curtains': typeof CurtainsRoute
  '/gallery': typeof GalleryRoute
  '/motorised-curtains': typeof MotorisedCurtainsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/quote': typeof ApiQuoteRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/zh-hans/about': typeof ZhHansAboutRoute
  '/zh-hans/blinds': typeof ZhHansBlindsRoute
  '/zh-hans/contact': typeof ZhHansContactRoute
  '/zh-hans/curtain-repairs': typeof ZhHansCurtainRepairsRoute
  '/zh-hans/curtains': typeof ZhHansCurtainsRoute
  '/zh-hans/gallery': typeof ZhHansGalleryRoute
  '/zh-hans/motorised-curtains': typeof ZhHansMotorisedCurtainsRoute
  '/zh-hans': typeof ZhHansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blinds': typeof BlindsRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/curtain-repairs': typeof CurtainRepairsRoute
  '/curtains': typeof CurtainsRoute
  '/gallery': typeof GalleryRoute
  '/motorised-curtains': typeof MotorisedCurtainsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/quote': typeof ApiQuoteRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/zh-hans/about': typeof ZhHansAboutRoute
  '/zh-hans/blinds': typeof ZhHansBlindsRoute
  '/zh-hans/contact': typeof ZhHansContactRoute
  '/zh-hans/curtain-repairs': typeof ZhHansCurtainRepairsRoute
  '/zh-hans/curtains': typeof ZhHansCurtainsRoute
  '/zh-hans/gallery': typeof ZhHansGalleryRoute
  '/zh-hans/motorised-curtains': typeof ZhHansMotorisedCurtainsRoute
  '/zh-hans/': typeof ZhHansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blinds'
    | '/blog'
    | '/contact'
    | '/curtain-repairs'
    | '/curtains'
    | '/gallery'
    | '/motorised-curtains'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/quote'
    | '/blog/$slug'
    | '/services/$slug'
    | '/zh-hans/about'
    | '/zh-hans/blinds'
    | '/zh-hans/contact'
    | '/zh-hans/curtain-repairs'
    | '/zh-hans/curtains'
    | '/zh-hans/gallery'
    | '/zh-hans/motorised-curtains'
    | '/zh-hans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blinds'
    | '/blog'
    | '/contact'
    | '/curtain-repairs'
    | '/curtains'
    | '/gallery'
    | '/motorised-curtains'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/quote'
    | '/blog/$slug'
    | '/services/$slug'
    | '/zh-hans/about'
    | '/zh-hans/blinds'
    | '/zh-hans/contact'
    | '/zh-hans/curtain-repairs'
    | '/zh-hans/curtains'
    | '/zh-hans/gallery'
    | '/zh-hans/motorised-curtains'
    | '/zh-hans'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blinds'
    | '/blog'
    | '/contact'
    | '/curtain-repairs'
    | '/curtains'
    | '/gallery'
    | '/motorised-curtains'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/quote'
    | '/blog/$slug'
    | '/services/$slug'
    | '/zh-hans/about'
    | '/zh-hans/blinds'
    | '/zh-hans/contact'
    | '/zh-hans/curtain-repairs'
    | '/zh-hans/curtains'
    | '/zh-hans/gallery'
    | '/zh-hans/motorised-curtains'
    | '/zh-hans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlindsRoute: typeof BlindsRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  CurtainRepairsRoute: typeof CurtainRepairsRoute
  CurtainsRoute: typeof CurtainsRoute
  GalleryRoute: typeof GalleryRoute
  MotorisedCurtainsRoute: typeof MotorisedCurtainsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiQuoteRoute: typeof ApiQuoteRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ZhHansAboutRoute: typeof ZhHansAboutRoute
  ZhHansBlindsRoute: typeof ZhHansBlindsRoute
  ZhHansContactRoute: typeof ZhHansContactRoute
  ZhHansCurtainRepairsRoute: typeof ZhHansCurtainRepairsRoute
  ZhHansCurtainsRoute: typeof ZhHansCurtainsRoute
  ZhHansGalleryRoute: typeof ZhHansGalleryRoute
  ZhHansMotorisedCurtainsRoute: typeof ZhHansMotorisedCurtainsRoute
  ZhHansIndexRoute: typeof ZhHansIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blinds': {
      id: '/blinds'
      path: '/blinds'
      fullPath: '/blinds'
      preLoaderRoute: typeof BlindsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curtain-repairs': {
      id: '/curtain-repairs'
      path: '/curtain-repairs'
      fullPath: '/curtain-repairs'
      preLoaderRoute: typeof CurtainRepairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curtains': {
      id: '/curtains'
      path: '/curtains'
      fullPath: '/curtains'
      preLoaderRoute: typeof CurtainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorised-curtains': {
      id: '/motorised-curtains'
      path: '/motorised-curtains'
      fullPath: '/motorised-curtains'
      preLoaderRoute: typeof MotorisedCurtainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quote': {
      id: '/api/quote'
      path: '/api/quote'
      fullPath: '/api/quote'
      preLoaderRoute: typeof ApiQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-hans/': {
      id: '/zh-hans/'
      path: '/zh-hans'
      fullPath: '/zh-hans/'
      preLoaderRoute: typeof ZhHansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-hans/about': {
      id: '/zh-hans/about'
      path: '/zh-hans/about'
      fullPath: '/zh-hans/about'
      preLoaderRoute: typeof ZhHansAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-hans/blinds': {
      id: '/zh-hans/blinds'
      path: '/zh-hans/blinds'
      fullPath: '/zh-hans/blinds'
      preLoaderRoute: typeof ZhHansBlindsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-hans/contact': {
      id: '/zh-hans/contact'
      path: '/zh-hans/contact'
      fullPath: '/zh-hans/contact'
      preLoaderRoute: typeof ZhHansContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-hans/curtain-repairs': {
      id: '/zh-hans/curtain-repairs'
      path: '/zh-hans/curtain-repairs'
      fullPath: '/zh-hans/curtain-repairs'
      preLoaderRoute: typeof ZhHansCurtainRepairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-hans/curtains': {
      id: '/zh-hans/curtains'
      path: '/zh-hans/curtains'
      fullPath: '/zh-hans/curtains'
      preLoaderRoute: typeof ZhHansCurtainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-hans/gallery': {
      id: '/zh-hans/gallery'
      path: '/zh-hans/gallery'
      fullPath: '/zh-hans/gallery'
      preLoaderRoute: typeof ZhHansGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-hans/motorised-curtains': {
      id: '/zh-hans/motorised-curtains'
      path: '/zh-hans/motorised-curtains'
      fullPath: '/zh-hans/motorised-curtains'
      preLoaderRoute: typeof ZhHansMotorisedCurtainsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlindsRoute: BlindsRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  CurtainRepairsRoute: CurtainRepairsRoute,
  CurtainsRoute: CurtainsRoute,
  GalleryRoute: GalleryRoute,
  MotorisedCurtainsRoute: MotorisedCurtainsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiQuoteRoute: ApiQuoteRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ZhHansAboutRoute: ZhHansAboutRoute,
  ZhHansBlindsRoute: ZhHansBlindsRoute,
  ZhHansContactRoute: ZhHansContactRoute,
  ZhHansCurtainRepairsRoute: ZhHansCurtainRepairsRoute,
  ZhHansCurtainsRoute: ZhHansCurtainsRoute,
  ZhHansGalleryRoute: ZhHansGalleryRoute,
  ZhHansMotorisedCurtainsRoute: ZhHansMotorisedCurtainsRoute,
  ZhHansIndexRoute: ZhHansIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
